from datetime import datetime
from models import ExtractedDocument, D365JournalLine
from config.settings import DEFAULT_CURRENCY

class AccountingRuleEngine:
    def build_initial_journal(self, doc: ExtractedDocument) -> D365JournalLine:
        today = datetime.now().strftime("%d/%m/%Y")
        if doc.document_type == "INVOICE":
            return D365JournalLine(
                journal_name="GenJrn",
                posting_date=doc.document_date or today,
                account_type=0,
                account_no="",
                description=doc.description or "Supplier invoice",
                debit_amount=round(doc.amount, 3),
                credit_amount=0,
                currency_code=doc.currency or DEFAULT_CURRENCY,
                exchange_rate=1,
                offset_account_type=2,
                offset_account=doc.matched_supplier or doc.supplier_name,
                invoice_no=doc.invoice_no,
                document_no=doc.document_no or doc.invoice_no,
                document_date=doc.document_date or today,
                due_date=doc.due_date or doc.document_date or today,
                country="KW",
                confidence=70,
                notes="Generated by AccountingRuleEngine",
            )
        return D365JournalLine(
            description=doc.description or doc.document_type,
            debit_amount=round(doc.amount, 3),
            currency_code=doc.currency or DEFAULT_CURRENCY,
            confidence=50,
            notes="Generic rule generated",
        )
